# Generated by Django 5.2.3 on 2025-07-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("article_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("brief_summary", models.TextField()),
                ("content", models.TextField()),
                ("published_date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
